In [1]:
# push system: people push onto the roads whenever they feel like
# pull system: system is pulling people when there is free capacity on the road

In [2]:
import pandas as pd
import numpy as np
import bokeh
from random import *
from itertools import count

### Definitions and Assumptions

**locations:** The road is seen as a vector from 0 to max
* offices are located 0 to 5
* factories are located 6 to 10
* housing areas are located 16 to 20


**economy:** It is assumed, that there are few large factories and a large number of small offices

**factories:** Large companies with inflexible/pushed workforce
* 80% of the workforce work in shifts and cannot leave the workplace as they like. They are pushed onto the streets
* 20% of the workforce can leave the workplace as they like. They can be pulled onto the streets

**offices:** Small companies with flexible/pullable workforce
* 20% of the workforce work in shifts and cannot leave the workplace as they like. They are pushed onto the streets
* 80% of the workforce can leave the workplace as they like. They can be pulled onto the streets

### Build the environment

In [13]:
class Work_site:
    
    def __init__(self, name, location, employees):
        self.name = name
        self.location = location
        self.employees = employees
        self.get_populated()
        
    def get_populated(self):
        
        self.workforce = {}
        for worker in range(0,self.employees):
            # Create an instance of Person and assign workplace to this workplace
            self.workforce["worker{0}".format(worker)] = Person()
            self.workforce["worker{0}".format(worker)].get_workplace(self)
            
            # of course, they need to live somewhere, too
            self.workforce["worker{0}".format(worker)].get_housing(sample(list_of_housing_areas, 1)[0])

In [14]:
class Person:
    
    _nr_of_people = 0
    
    def __init__(self):
        Person._nr_of_people += 1
        self.id = Person._nr_of_people
        
        list_of_persons.append(self)
    
    def get_workplace(self, workplace):
        self.workplace = workplace
        
    def get_housing(self, housing):
        self.housing = housing

In [15]:
class Housing_area:
    
    def __init__(self, name, location):
        self.name = name
        self.location = location

In [57]:
# set counters to zero and empty lists
list_of_persons = []
Person._nr_of_people = 0

In [58]:
nr_of_factories = 3
nr_of_offices = 3
nr_of_housing_areas= 6

list_of_persons = []

list_of_housing_areas = [0] * nr_of_housing_areas
for housing in range(0, nr_of_housing_areas):
    name = 'housing' + str(housing + 1)
    location = randint(16,20)
        
    list_of_housing_areas[housing] = Housing_area(name, location)

list_of_factories = [0] * nr_of_factories
for factory in range(0, nr_of_factories):
    name = 'factory' + str(factory + 1)
    location = randint(6,10)
    employees = randint(6,10)
    
    list_of_factories[factory] = Work_site(name, location, employees)

In [59]:
df_persons = pd.DataFrame(columns = ['id', 'workplace', 'workplace_loc', 'housing', 'housing_loc'])

for person in list_of_persons:
    df_persons = df_persons.append({'id': person.id,
                       'workplace': person.workplace.name,
                       'workplace_loc': person.workplace.location,
                       'housing': person.housing.name,
                       'housing_loc': person.housing.location},
                                 ignore_index = True)
    
df_persons['commute'] = df_persons.housing_loc - df_persons.workplace_loc

df_persons

    id workplace workplace_loc   housing housing_loc commute
0    1  factory1             9  housing5          17       8
1    2  factory1             9  housing3          18       9
2    3  factory1             9  housing4          20      11
3    4  factory1             9  housing3          18       9
4    5  factory1             9  housing2          19      10
5    6  factory1             9  housing5          17       8
6    7  factory1             9  housing1          17       8
7    8  factory1             9  housing4          20      11
8    9  factory1             9  housing3          18       9
9   10  factory1             9  housing6          18       9
10  11  factory2             8  housing6          18      10
11  12  factory2             8  housing4          20      12
12  13  factory2             8  housing6          18      10
13  14  factory2             8  housing3          18      10
14  15  factory2             8  housing5          17       9
15  16  factory2             8  housing3          18      10
16  17  factory2             8  housing2          19      11
17  18  factory2             8  housing4          20      12
18  19  factory3             7  housing5          17      10
19  20  factory3             7  housing6          18      11
20  21  factory3             7  housing6          18      11
21  22  factory3             7  housing5          17      10
22  23  factory3             7  housing4          20      13
23  24  factory3             7  housing6          18      11